name: alicsnet_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.27.41+221214023

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #
  simple_animations: ^4.0.2
  shared_preferences: ^2.0.13
  speech_to_text: ^5.4.3
  avatar_glow: ^2.0.2
  http: ^0.13.4
  flutter_tts: ^3.3.3
  flutter_easyloading: ^3.0.3
  font_awesome_flutter: ^10.1.0
  in_app_purchase: ^3.0.2
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  auto_size_text: ^3.0.0
  fl_chart: ^0.50.6
  flutter_web_frame: ^0.0.2

  percent_indicator: ^4.0.1
  # About Login
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  firebase_dynamic_links: ^4.2.1
  google_sign_in: ^5.3.0
  sign_in_with_apple: ^3.3.0

  auto_route: ^3.2.4
  crypto: ^3.0.2

  #
  wakelock: ^0.6.1
  flutter_emoji: ^2.0.0

dev_dependencies:
  build_runner:
  auto_route_generator: ^3.2.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/sels_app/
    - assets/sounds/
    - assets/icon/
    - assets/sels_app/GrammarCheckPage/
    - assets/sels_app/PhoneticExercisesLearnManualPage/
    - assets/sels_app/SELSAppHomePage/
    - assets/sels_app/LoginPage/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Deafult
      fonts:
        ## English
        #- asset: fonts/arialn.ttf
        #- asset: fonts/arial_th.ttf
        #- asset: fonts/arial_mt_black.ttf
        ## Traditional Chinese
        #- asset: fonts/NotoSerifTC-Black.otf
        #- asset: fonts/NotoSerifTC-Bold.otf
        #- asset: fonts/NotoSerifTC-ExtraLight.otf
        #- asset: fonts/NotoSerifTC-Light.otf
        #- asset: fonts/NotoSerifTC-Medium.otf
        #- asset: fonts/NotoSerifTC-Regular.otf
        #- asset: fonts/NotoSerifTC-SemiBold.otf
        # Unicode-encoded
        - asset: fonts/NotoSerif-Bold.ttf
        - asset: fonts/NotoSerif-BoldItalic.ttf
        - asset: fonts/NotoSerif-Italic.ttf
        - asset: fonts/NotoSerif-Regular.ttf
